### ISSUE TITLE
"Parsing failed" with #error

### ISSUE THREAD

**Issue by Gama11** [Simn/haxeparser#29]
Discovered this when running haxe-checkstyle on the std lib. Seems like haxeparser simply doesn't know about `#error`.

```haxe
C:\HaxeToolkit\haxe\std/Std.hx:1: character 0 : Error: Parsing failed: { msg => Custom(Please don't add haxe/std to your classpath, instead set HAXE_STD_PATH env var), pos => { file => C:\HaxeToolkit\haxe\std/Std.hx, max => 1177, min => 1171 } }
Stacktrace: 
Called from haxeparser/HaxeParser.hx line 131
Called from hxparse/Parser.hx line 36
Called from hxparse/ParserBuilderImpl.hx line 112
Called from haxeparser/HaxeParser.hx line 265
Called from Checker.hx line 115
Called from Checker.hx line 148
```

**Comment by Simn** [comment]
Did you try that with the development version? I'm pretty sure I have parsed the entire standard library with haxeparser.

**Comment by Gama11** [comment]
The development version of what, Haxe? I'm currently on 3.2.0.

**Comment by Simn** [comment]
Of haxeparser

**Comment by Gama11** [comment]
There doesn't really seem to be a development version right now, since master is up to date with the latest haxelib release? And haxe-checkstyle uses that version (3.2.0).

**Comment by Simn** [comment]
Oh, I didn't remember I actually made a haxelib release at some point.

This actually works as expected, if you check Std.hx you'll find that the message you're seeing is the one coming from the `#error` itself. Try defining "cross" via https://github.com/Simn/haxeparser/blob/master/src/haxeparser/HaxeParser.hx#L259.

**Comment by Simn** [comment]
P.S.: I just checked, haxeparser makes it through the entire std directory with the defines "cross", "scriptable" and "unsafe". See https://github.com/Simn/haxeparser/blob/master/test/TestStd.hx.

**Comment by Simn** [comment]
P.S.2: If you know how to we can add that to travis by the way. All it requires is adding this with the correct path to build.hxml:

```
-D haxe_std_path=C:\github\haxe\std
```
